version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: denglt/friendlyhello:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks:
      - webnet
networks:
  webnet:

# docker stack deploy -c docker-compose.yml getstartedlab

# 手动 create  service
#docker@myvm1:~$ docker service create --replicas 2 --name myservice --network my-attachable-overlay   denglt/friendlyhello
#paswn8n4sv7dzz8nxkeddb357
#overall progress: 2 out of 2 tasks
#1/2: running   [==================================================>]
#2/2: running   [==================================================>]
